# Service Discovery
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://172.18.0.5:8761/eureka/
spring:
  application:
    name: gatewayService

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
